gretelai/trainer

notebooks/gretel-trainer-conditioning.ipynb, notebooks/gretel-trainer.ipynb
This removes the `PROJECT.delete()` instruction from our notebooks. `run.cancel_all()` isn't blocking, so what will happen is: the models will get cancelled, the project deleted, and then models will error as they go into a cancelled state because the models or project no longer exist.
An alternative approach is to make `Job.cancel()` block from `gretel-client`, but this might be a larger task we want to plan out.
=> Remove project delete instruction

src/gretel_trainer/runner.py, src/gretel_trainer/trainer.py
A few ways we could slice and dice this; I figure there may be additional SQS info we want from the run in the future so I decided to expose the entire `List[dict]` from the runner, and let the trainer pluck out and calculate the first such aggregate, user-friendly data. I'm open to pushing more of this down to the runner and/or transforming the SQS dictionaries into first-class types (likely dataclasses) if anyone has a strong opinion or thinks it'd be useful.
=> Get average sqs score from across partitions

src/gretel_trainer/models.py, src/gretel_trainer/runner.py, src/gretel_trainer/strategy.py, src/gretel_trainer/trainer.py, tests/test_strategy.py
Rather than create a `GretelAuto` model class that would need to override or work around several `_BaseConfig` details (validation, max/limit values, etc.), my goal here is to establish the convention that model type is optional and if you don't specify one when instantiating the Trainer, you're OK with us choosing for you. This is a change from the current behavior (optional but default to LSTM). In this case, we defer setting the trainer instance's `self.model_type` until such time as we can determine the best model to use: namely, at train time when a dataset has been provided.
I'm a little unclear on the `load` (from cache) workflow, which in this branch's implementation would set the StrategyRunner's `model_config` to `None`. I think this is OK because the only methods referencing …
=> Auto-determine best model from training data

src/gretel_trainer/runner.py, src/gretel_trainer/trainer.py
Add original file name to data sources uploaded as part of trainer projects. This helps disambiguate the data sources from multiple trainer runs where previously they were always named `trainer_0.csv`, `trainer_1.csv`, etc.
Also fixes `StrategyRunner` to not silently swallow all `ApiException`s when submitting a job, so errors not associated with max job limit are still thrown and surfaced to the user.
=> Include dataset name in trainer uploads.

notebooks/trainer-examples.ipynb, src/gretel_trainer/models.py, src/gretel_trainer/trainer.py
Adds support for [Gretel Amplify](https://docs.gretel.ai/gretel.ai/synthetics/models/amplify) to trainer.
=> Add support for Gretel Amplify

src/gretel_trainer/benchmark/compare.py, src/gretel_trainer/benchmark/gretel/sdk.py, tests/test_benchmark.py
When running in an environment where no Gretel credentials can be found (e.g. Colab), when Benchmark kicks off a comparison the background threads instantiating Trainer instances will prompt for an API key. This is problematic for multiple reasons, all (I believe) due to it running in multiple background threads: it prompts multiple times, doesn't accept input and/or cache properly, and ultimately crashes.
Benchmark itself now checks for a configured session before kicking off any real work. It prompts (`api_key="prompt"`) if no credentials are found, validates (`validate=True`) the supplied API key, and caches (`cache="yes"`) it for all the runs it manages. The `configure_session` calls that happen when instantiating Trainer effectively "pass through." I've tested this by installing …
=> Configure session before starting Benchmark comparison

src/gretel_trainer/benchmark/compare.py
Quick fix so that benchmark's internal run identifier lines up with the project name in Gretel Cloud. We'll eventually have a more user-friendly and stable interface to access detailed run information, but until we figure out how exactly we want that to look and do it, this should make things a little more friendly for those willing to dive into the internals: the models from project `benchmark-{timestamp}-3` will correspond to `comparison.results_dict["gretel-3"]` (instead of `"gretel-4"`)
Note: I considered just using the full project name as the identifier instead of `gretel-{index}`, but we don't have an equivalent to project names for user custom model runs, so I figure the current `[gretel|custom]-{index}` approach is still best for now.
=> Fix off-by-one difference between project name and run ID

src/gretel_trainer/runner.py
Particularly given that we now have a third model (Amplify) supported in Trainer, we can remove this no-op `elif` clause so that the runner only has special logic for / awareness of LSTM (expand up in the diff for context).
=> Remove no-op elif case from runner

setup.py
The previous name "relational" was a bit misleading, since you don't need to install those extras to use the relational module generally; they are only required for various connectors.
This change gives a clearer name to that extras package, and also splits by db type to allow finer-grained package installation if desired.
=> Rename and split connector extras

src/gretel_trainer/relational/connectors.py
Testing with snowflake revealed that, while the previously-optional arguments are optional for creating a SQLAlchemy engine generally, for our particular usage of it in the `Connector#extract` method we really need to provide all those arguments; otherwise, sqlalchemy complains during extraction and you just have to start over making a new connection with more arguments supplied. We can nip that in the bud by requiring them all up front.
I updated the other helpers to require a specific database so that we don't try connecting to some multi-db host and extracting an obscene amount of data.
Finally, for sanity purposes, the functions all require keyword arguments, no positional nonsense.
Since these functions are only helpers for creating SQLAlchemy engines, if any of these opinions are …
=> Be more opinionated in connector helper functions

src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/independent.py
Builds a list of parent indices and merges parent data all at once instead of extracting and appending entire records in each iteration of a large loop.
Also drops `itertools.cycle` (from both strategies) and "reverts" back to classic index-incrementing given `cycle`'s [warning about auxiliary storage requirements](https://docs.python.org/3/library/itertools.html#itertools.cycle).
=> Seed performance

requirements.txt
This is the most recent version that supports python 3.7, which is what Colab runs.
=> Downgrade networkx to continue supporting python 3.7

.github/workflows/build.yml, src/gretel_trainer/relational/ancestry.py, tests/relational/test_independent_strategy.py
- Two internal code locations where we had been using methods that aren't in 3.7
- Our matrix CI build was running on 3.9 in both builds 🤦 , this has been fixed so we test against both 3.9 and 3.7
=> Internal 3.7 support

src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/sdk_extras.py, tests/relational/test_multi_table.py
Instead of waiting to upload source CSVs to the project until calling `train`, with this change we will upload them when the MultiTable instance is created. Two reasons for this:
1. Allows restoring from just a created MT instance that hasn't "done" anything yet. Probably not a common use case, but if nothing else it's easier to describe/document the behavior.
2. By uploading the source artifacts right away, we'll be able to (re)use them for transforms.
=> Upload source on init

notebooks/relational.ipynb, src/gretel_trainer/relational/multi_table.py, tests/relational/test_multi_table.py
- Reduce max retry count on lost-ish jobs from 5 to 3
- Reduce minimum refresh interval to 30s, default to 60s
- Add job status (created/active/pending) to in-progress log statement
- Drop `state_by_[action|table]` methods
=> Fast follow

src/gretel_trainer/relational/multi_table.py
- Fix missing keyword arg to `get_project`
- Prevent nested files in archives—add all files at archive root level
- Create working dir during restore if it doesn't exist (e.g. loading backup file from some other location)
=> Restore fixes

src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/common.py, tests/relational/conftest.py, tests/relational/example_dbs/art.sql, tests/relational/test_ancestral_strategy.py, tests/relational/test_independent_strategy.py
Updates to how AncestralStrategy prepares training data:
- translates all keys (numeric or alphanumeric) to contiguous integers
- drops highly-NaN ancestral fields from training data (this is in addition to dropping highly-unique categorical ancestral fields, which we were already doing)
- adds new artificial records with min/max PK/FK values (instead of modifying existing records)
=> Preprocessing updates

src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/common.py, src/gretel_trainer/relational/strategies/independent.py, tests/relational/test_relational_data.py
Improvements to various sad-path scenarios, including:
- Flip order of job-status-check / max-refresh-attempts-bailout so that we don't needlessly wait `refresh_interval` seconds between final status check and bail
- Under ancestral strategy, skip generation jobs for descendant tables if we lose contact with a parent table
- Under independent strategy, skip cross_table evaluation if any parent tables failed and are unavailable
- Under independent strategy, keep synthetic data but set FK values to `None` when child generates successfully but parent fails
- Avoid potential KeyError in transforms
=> Sad path improvements

src/gretel_trainer/relational/__init__.py, src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/report/report.py, src/gretel_trainer/relational/report/report_template.html
The relational report had been showing the generated-at time in UTC. Meanwhile, our default run identifier (when a user doesn't specify one) is the current time in the user's local timezone. (Note also, those two times won't match even regardless of timezone because one is set before generation begins, the other after it completes.)
This change removes the generated-at time from the relational report and replaces it with the run identifier (whether default local timestamp or user-specified string), making it easier for users to associate a report with a specific subdirectory of synthetic data (particularly when running generate multiple times).
=> Show run ID instead of generated at time in relational report

src/gretel_trainer/models.py
This parameter was deprecated in version `0.5.0`, released November 18, 2022. Current version of Trainer is `0.6.5`, and we're preparing for a `0.7.0` release. Can we drop these completely now in advance of `0.7.0`?
=> Drop deprecated enable_privacy_filters param from Trainer models

src/gretel_trainer/relational/report/report.py, src/gretel_trainer/relational/report/report_template.html
Relational report sub-header under title will now follow format
Generated {YYYY-mm-dd}
Run ID: {run_identifier}
=> Include both date of generation and run ID in report header

src/gretel_trainer/relational/artifacts.py, src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/report/report.py, src/gretel_trainer/relational/sdk_extras.py, tests/relational/test_multi_table_restore.py
Adds project artifact eviction logic to Relational Trainer to prevent running into project artifact limits during runtime. We delete any project artifacts associated directly with a singular job (e.g. a model training dataset, or a seed file for conditional generation) when the job completes (or fails/is marked lost), so when "nothing is going on" we should expect to see some/all of the following artifacts (in order of when they'd be added, typically):
```
_gretel_backup.json
_gretel_debug_summary.json
source_tables.tar.gz
transforms_outputs.tar.gz
synthetics_training.tar.gz
synthetics_outputs.tar.gz
```
When we queue up jobs, once we reach the artifact limit we hold off on deferring additional jobs until there is more room in the project. This runs on the same `refresh_interval` check as …
=> Relational eviction

src/gretel_trainer/benchmark/gretel/sdk.py
Literally the latest release (1.1.299) of pyright has started throwing an error at this line; I'm not sure what the problem is and/or if it's a regression on the pyright side—for now this comment will fix the build and not cause any problems; we can revisit in greater detail later.
=> Ignore pyright issue with poll

Makefile, requirements-dev.txt, src/gretel_trainer/benchmark/custom/datasets.py, src/gretel_trainer/benchmark/gretel/executor.py, src/gretel_trainer/benchmark/gretel/models.py, src/gretel_trainer/benchmark/gretel/trainer.py, src/gretel_trainer/models.py, src/gretel_trainer/runner.py, src/gretel_trainer/strategy.py, src/gretel_trainer/trainer.py, tests/relational/test_synthetics_run_task.py, tests/test_benchmark.py, tests/test_strategy.py
While working on hybrid support, I thought I'd tackle the pyright warnings so that we can type check the entire codebase (previously had been limited to Benchmark and Relational). Some notes:
- I punted on some of the Benchmark warnings (`# type:ignore`) because Benchmark v2 is on the horizon
- I didn't see any public method on `StrategyRunner` that didn't ultimately call the `needs_load` wrapper, so I decided to just refactor such that that is called during init instead of decorating basically every method
- Dropped `StrategyRunner.from_completed` as it is unused (perhaps it was supplanted by `Trainer.load`, which appears to do the same thing)
- I didn't see anything setting `PartitionConstraints max_row_partitions`. Not sure if this had been used and was deprecated/removed, or if it had …
=> Trainer types

notebooks/conditional-generation.py, notebooks/custom-example.py, notebooks/simple-conditional-generation.ipynb, notebooks/simple-example.py, notebooks/trainer-examples.ipynb, requirements.txt, src/gretel_trainer/runner.py, src/gretel_trainer/trainer.py
- Use the generic `submit` method on jobs (which relies on the session config, see more below)
- Skip artifact eviction when in hybrid mode (we can't delete hybrid artifacts, but we don't need to anyways because we don't have an artifact limit to worry about)
Cloud vs. Hybrid is driven by the client config. Lifting this function out of the library code separates concerns and avoids cluttering the Trainer interface with configuration details. I updated all the (non-Benchmark/Relational) notebooks and examples to explicitly call `configure_session` first separately. (Relational coming in a separate PR.)
=> Hybrid trainer

notebooks/relational.ipynb, src/gretel_trainer/relational/__init__.py, src/gretel_trainer/relational/artifacts.py, src/gretel_trainer/relational/log.py, src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/sdk_extras.py, src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/common.py, src/gretel_trainer/relational/strategies/independent.py, src/gretel_trainer/relational/task_runner.py, src/gretel_trainer/relational/tasks/common.py, src/gretel_trainer/relational/tasks/synthetics_run.py, src/gretel_trainer/relational/tasks/transforms_run.py, tests/relational/conftest.py, tests/relational/test_ancestral_strategy.py, tests/relational/test_artifacts.py, tests/relational/test_backup.py, tests/relational/test_independent_strategy.py, tests/relational/test_multi_table_restore.py, tests/relational/test_synthetics_run_task.py, tests/relational/test_task_runner.py
These changes will also require gretel-client 0.16.0, which I specified in the requirements file in the PR for trainer. I'll rebase this PR atop that one once it lands.
As with Trainer, I've lifted `configure_session` out of the library code. We should add a `configure_session` cell to the UCC notebooks.
We do not upload relational-specific artifacts in hybrid mode. This includes the debug summary, backup file, and archive files (source, xforms outputs, synthetics training, synthetics outputs). The reason for this is that all of these relational artifacts are intended to be "singleton" objects that get overwritten when/as state changes. Examples:
- backup file: we take backup snapshots quite often throughout all processes
- xforms/synthetics outputs archives: each time you run record …
=> Hybrid relational

requirements-dev.txt
The [latest release (1.1.306)](https://github.com/microsoft/pyright/releases/tag/1.1.306) of pyright includes several bug fixes that expose quite a few more type hint issues in this codebase. As a short term fix, I'm pinning pyright to the previous version to unblock higher-priority work; we can come back to address these some other time.
Many (but not all) of the new warnings from the latest pyright fall into a few categories:
- `Job` vs. `Model | RecordHandler`
- `smart_open` context managers (I think this might be a new bug on pyright's side? The message seems wrong to me)
- Several places where we hint job IDs as `str` but pyright thinks they are `str | None` (which is fair—IDs are None when first created and only get created once the job is submitted)
=> Pin pyright to 1.1.305

src/gretel_trainer/relational/report/report_template.html
I missed this in #100 when we turned all the keys into lists 😞  Fortunately we haven't released yet so this is only broken on `main` branch, not in the latest public version on PyPi.
=> Fix FKs in relational report

requirements-dev.txt, src/gretel_trainer/benchmark/comparison.py, src/gretel_trainer/benchmark/core.py, src/gretel_trainer/benchmark/custom/datasets.py, src/gretel_trainer/benchmark/custom/strategy.py, src/gretel_trainer/benchmark/executor.py, src/gretel_trainer/benchmark/gretel/datasets.py, src/gretel_trainer/benchmark/gretel/models.py, src/gretel_trainer/benchmark/gretel/strategy_sdk.py, src/gretel_trainer/benchmark/sdk_extras.py, tests/benchmark/test_benchmark.py
This PR modifies b2 in a few ways I have found convenient:
- Support for quality scores other than SQS in the comparison table, via the `additional_report_scores` param (e.g., `additional_report_scores=["FCS", "PCS", "FDS"]`)
- Key runs by `(model, dataset)` pairs instead of `{model}-{dataset}` string. The latter can not be parsed unambiguously if the model or dataset names contain a dash.
- Support for marking datasets as public to avoid uploading them (note: this no longer works in most recent Python client release, though)
- Support instances in the `models` list instead of just classes (classes still work). This mostly enables the next item:
- Adds a `configure_model` function, that allows overriding the name and/or config of a model.
=> Convenience modifications to b2

notebooks/relational.ipynb, src/gretel_trainer/relational/connectors.py, src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/multi_table.py, tests/relational/conftest.py, tests/relational/test_relational_data.py
An earlier branch that has been merged to `main` but not yet released included a breaking change to the `add_foreign_key` method. This PR restores the original method signature (for backwards compatibility) with a deprecation warning (docstring + logged), and introduces a new method (same name plus the `_constraint` suffix) with the preferred (more explicit, less magical, supports composite keys) arguments.
=> Restore old FK interface but with deprecation warnings

src/gretel_trainer/relational/ancestry.py, src/gretel_trainer/relational/backup.py, src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/model_config.py, src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/report/figures.py, src/gretel_trainer/relational/report/report.py, src/gretel_trainer/relational/sdk_extras.py, src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/common.py, src/gretel_trainer/relational/strategies/independent.py, src/gretel_trainer/relational/task_runner.py, src/gretel_trainer/relational/tasks/classify.py, src/gretel_trainer/relational/tasks/synthetics_evaluate.py, src/gretel_trainer/relational/tasks/synthetics_run.py, src/gretel_trainer/relational/tasks/synthetics_train.py, src/gretel_trainer/relational/tasks/transforms_run.py, src/gretel_trainer/relational/tasks/transforms_train.py, src/gretel_trainer/relational/workflow_state.py, tests/relational/conftest.py, tests/relational/test_multi_table_restore.py, tests/relational/test_synthetics_run_task.py, tests/relational/test_task_runner.py
I had been just cleaning these as I go but it just got distracting both to myself and in PRs, so I decided to just clean it all up in one fell swoop (big thanks to [fastmod](https://github.com/facebookincubator/fastmod)).
Note: this is a branch off a branch where I had already started some of this more manually.
=> Kill off all the old style types in Relational code

src/gretel_trainer/relational/backup.py, src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/json.py, src/gretel_trainer/relational/multi_table.py, tests/relational/test_backup.py, tests/relational/test_relational_data_with_json.py
When parsing JSON, it's possible for all values to contain some empty list value—for example, in the unit tests `bball` fixture, each player has a `suspensions` key with empty list value. We want to be able to restore this field in the final denormalized/original-matching output data, but we **don't** want to submit an empty table for training.
We now include add empty invented tables to the graph (so we know where to put them back when denormalizing), but ensure they are not exposed to clients asking for MODELABLE tables.
As before this branch, we still do not support dataframes where _all columns_ contain JSON lists. Fortunately, as the unit test changes demonstrate, these changes have the added benefit of detecting that sooner and avoiding ending up in a bad state when this edge case …
=> Fix bug related to empty normalized tables

src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/independent.py, tests/relational/test_ancestral_strategy.py, tests/relational/test_independent_strategy.py
Currently, the preprocessing in synthetics training creates a training DF for each table, keeps each of those in a dictionary, and passes the dictionary to the next method which writes each to a CSV and submits a model.
With this change, each training DF is written to CSV as soon as it is created, so we don't have to hold on to more than one at a time.
There's also a small change to the independent strategy specifically: instead of asking for the whole source dataframe and then dropping columns, we only ask for the columns we intend to keep. This doesn't make too big a difference now (since the whole source DF is already in memory in the graph), but we anticipate eventually storing source data on disk and loading in the data when needed, and presumably at that point this will provide some …
=> Write and drop

src/gretel_trainer/relational/model_config.py, src/gretel_trainer/relational/multi_table.py, tests/relational/test_model_config.py, tests/relational/test_train_synthetics.py
With these changes, users are no longer limited to the synthetics blueprints configs and can provide fully customized model configs. You can supply one "main" config as well as table-specific configs if you want to get that granular:
```python
mt.train_synthetics(
config=my_tabular_dp_config,
table_specific_configs={"table_x": my_actgan_config},
)
```
~~Are these parameter values sufficiently clear? I didn't particularly like using the word "overrides" (e.g. `table_config_overrides`) because that feels to me like it'd be expecting "field-level" overrides on top of the `config` as a "base template", when in fact we are requiring _fully formed configs_ in both places.~~ EDIT: going with `table_specific_configs`
I recommend looking at the unit tests added to the diff for some behavior …
=> Custom synthetics configs

src/gretel_trainer/relational/extractor.py
Fixes a few Dask-isms. The `drop_duplicates()` is still a bit of a mystery to me. I haven't dug into the root cause of why the columns need to be artificially subsetted first, but it definitely impacts things. The second issue with `map_partitions` was a little more straight forward since the docs for that method mention the dummy data that gets created.
=> table extractor dask fixes

src/gretel_trainer/relational/multi_table.py, src/gretel_trainer/relational/strategies/ancestral.py, src/gretel_trainer/relational/strategies/independent.py, tests/relational/test_train_synthetics.py
Adds deprecation warnings guiding the user _away from_:
```python
mt = MultiTable(rel_data, gretel_model="amplify")
mt.train_synthetics()
```
...and _towards_:
```python
mt = MultiTable(rel_data)
mt.train_synthetics(config="synthetics/amplify")
```
Each line in the first block above will print a deprecation warning (but will continue to work). In a future release we'll remove the `gretel_model` parameter completely and make `config` a required argument to `train_synthetics`.
In the [previous PR](https://github.com/gretelai/trainer/pull/120) adding custom synthetics config support, I reused the existing `supported_models` property of the strategies for config validation. However, those values are essentially constants specific to Relational Trainer (the `gretel_model` param specifically); …
=> Deprecation warnings + bugfix

src/gretel_trainer/relational/backup.py, src/gretel_trainer/relational/multi_table.py, tests/relational/test_backup.py
In the PR for column order (https://github.com/gretelai/trainer/pull/123), I added `columns` as a required field on the backup table dataclass, but we don't actually read that value back during the restore process. This PR drops that field so that backup files should be backwards-compatible a little while longer. (I believe we will need to add `columns` in the future, but hey, maybe not!).
Two other small changes here:
- When writing source data from CSV to DF (to upload in the `source_tables.tar.gz` archive), provide the columns argument explicitly. This probably doesn't have any effect in most cases, but is consistent with how we write our transforms and synthetics output files.
- The restore process was logging a deprecation warning about the `gretel_model` argument even though the …
=> Backup cols

src/gretel_trainer/relational/backup.py, src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/json.py, src/gretel_trainer/relational/multi_table.py, tests/relational/test_backup.py, tests/relational/test_relational_data_with_json.py
No user-facing changes here, strictly an internal refactor.
Previously, tables with JSON columns got "extra special treatment": after creating invented tables from them, we added the invented tables to the `RelationalData` graph as nodes, but _not_ the source table itself; instead, metadata about that original table was stored in a `RelationalJson` object responsible for knowing everything necessary to transform invented tables back to the original shape. Then the `RelationalData` stored a dictionary of those objects. This was always a bit clunky and added a lot of mental overhead when trying to reason about the internal state.
In the spirit of "cattle, not pets", this PR makes what we now call "producer" tables more similar to normal and invented tables. Probably the key takeaway is that …
=> Core refactors

src/gretel_trainer/relational/connectors.py, src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/extractor.py, src/gretel_trainer/relational/json.py, src/gretel_trainer/relational/multi_table.py, tests/relational/conftest.py, tests/relational/test_ancestral_strategy.py, tests/relational/test_ancestry.py, tests/relational/test_common_strategy.py, tests/relational/test_connectors.py, tests/relational/test_relational_data.py, tests/relational/test_relational_data_with_json.py, tests/relational/test_train_transforms.py
Instead of storing tables' source data as Pandas DataFrames in memory, store them as CSV files on disk. Users can now provide either a dataframe or a string/Path to a CSV when calling `add_table`.
I did some initial profiling using the [Airline db from relational fit](https://relational.fit.cvut.cz/dataset/Airline), which self-reports as being 455MB. I used [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) to measure both the "resting memory footprint" at certain checkpoints, as well as the peak memory size between those checkpoints. The table compares current released code on main / Trainer 0.9.0 with the code on this branch. 
Using the first row and main branch as an example, the way to read this table is:
> While running on `main` branch, after instantiating a …
=> Source on disk

notebooks/benchmark.ipynb, src/gretel_trainer/benchmark/__init__.py, src/gretel_trainer/benchmark/comparison.py, src/gretel_trainer/benchmark/core.py, src/gretel_trainer/benchmark/custom/datasets.py, src/gretel_trainer/benchmark/custom/strategy.py, src/gretel_trainer/benchmark/executor.py, src/gretel_trainer/benchmark/gretel/datasets.py, src/gretel_trainer/benchmark/gretel/datasets_backwards_compatibility.py, src/gretel_trainer/benchmark/gretel/models.py, src/gretel_trainer/benchmark/gretel/strategy_sdk.py, src/gretel_trainer/benchmark/gretel/strategy_trainer.py, src/gretel_trainer/benchmark/sdk_extras.py, tests/benchmark/test_benchmark.py, tests/benchmark/test_custom_datasets.py, tests/benchmark/test_gretel_datasets_repo.py
This PR includes changes to merge into the `b2` branch (not `main` yet!) that will ease users' transition from Benchmark v1 to v2 once we fully merge and release v2. It does not make that upgrade **fully** backwards compatible—there are still some breaking changes—but it should at least be a little smoother.
Since several people are already running Benchmark from the `b2` branch, I'll describe the changes in this PR from both perspectives. The sections below present the user-facing changes from `[section header]` to `[this branch]`; in other words, if we were to merge this PR _and_ merge b2 branch into main _and_ run a release of Trainer, these are the changes you'd have to address to start using the officially released Benchmark, depending on what you're using today.
- …
=> B2 backwards compatibility

README.md, tests/relational/conftest.py
A large portion of the unit tests were failing for me with a fresh clone of this repository on a brand new m2 macbook. Upon further digging I was able to identify sqlite3.connect as the issue. Specifically it wasn't honoring the uri params passed in the connection string and so it was creating a db on disk rather than an in memory shared db. This caused unit tests to throw errors.
ref: https://stackoverflow.com/questions/62502827/python-how-to-connect-sqlalchemy-to-existing-database-in-memory
=> fix: unit test errors on new mac m2

src/gretel_trainer/relational/strategies/independent.py
For independent synthetics, the data source we use for the model is identical to the source data except PK and FK columns are removed. Now that we have source data stored on disk instead of in memory, this small code block seemed annoying—read the whole dataframe (minus key columns) into memory only to write it right back out to CSV? Blegh.
This change at least limits the memory usage by reading and writing in chunks.
I extracted these two basic implementations and ran an experiment with tracemalloc using a 400MB CSV file. Using the previous approach, traced memory peaked at 977,813,835. When using chunks, traced memory peaked at 232,618,553.
There may be some future improvements to this (and other areas of the code) leveraging Dask, but that requires more research and testing. (In fact, …
=> Chunked independent synthetics preprocessing

pyproject.toml, src/gretel_trainer/relational/core.py, src/gretel_trainer/relational/json.py, tests/relational/conftest.py, tests/relational/test_backup.py, tests/relational/test_relational_data_with_json.py, tests/relational/test_train_synthetics.py
In cases where we are parsing nested json with lengthy key strings the combination of key strings in the breadcrumb based table name string would result in an error when trying to train the model due to a maximum json filename length of 128 chars. Here we utilize the already existing make_suffix function (which ensures no sanitized_str collisions) and we truncate the length of the table name to ensure we do not exceed the 128 char limit.
=> fix: nested json table string length

src/gretel_trainer/relational/__init__.py
So that we can do
```python
from gretel_trainer.relational import ExtractorConfig
```
=> Expose ExtractorConfig from root relational module

src/gretel_trainer/relational/multi_table.py
In [the PR](https://github.com/gretelai/trainer/pull/130) moving source data from memory to disk, I introduced a bug in the creation of the source data archive (`source_tables.tar.gz`) that broke the restore-from-backup functionality.
- Write each source table from Pandas DataFrame to a local CSV named `source_{table}.csv`
- Archive those files, upload the tar to the project as a project artifact
- When restoring from backup file, pull down the archive, unpack, and read those files back into DataFrames
Since the tables now exist on disk and we only store pointers to them in memory, we don't need to call `dataframe.to_csv`; instead we just add the existing local files to the archive. The problem is that the filenames of the archived files changed—they no longer had the `source_` prefix but …
=> Re-add source_ prefix to archived source files

src/gretel_trainer/relational/artifacts.py, src/gretel_trainer/relational/task_runner.py, src/gretel_trainer/relational/tasks/common.py
Just a few import changes I noticed
=> Clean up some imports

.github/workflows/build.yml, requirements.txt, test-requirements.txt
- numpy is imported explicitly in the `relational.extractor` and `relational.json` modules, but had not been declared an official dependency (it was getting pulled in transitively by pandas)
- rename dev/test requirements file to be consistent with our other public Python repos (gretel-client, gretel-synthetics)
- similarly, take out the `-r requirements.txt` helper and just explicitly install both files during workflow setup
- I believe we could get away with only installing `-r test-requirements.txt` explicitly, and then the following `pip install -e .` line would handle installing the production/runtime requirements thanks to `install_requires` in `setup.py`. I don't have a strong opinion here.
- alphabetizing is good for you
=> Dependency tweaks

requirements.txt, src/gretel_trainer/benchmark/__init__.py, src/gretel_trainer/benchmark/comparison.py, src/gretel_trainer/benchmark/core.py, src/gretel_trainer/benchmark/entrypoints.py, src/gretel_trainer/benchmark/executor.py, src/gretel_trainer/benchmark/gretel/strategy_sdk.py, src/gretel_trainer/benchmark/gretel/strategy_trainer.py, src/gretel_trainer/benchmark/job_spec.py, src/gretel_trainer/benchmark/session.py, tests/benchmark/conftest.py, tests/benchmark/test_bad_setup.py, tests/benchmark/test_benchmark.py
Introduces `Session` as an encapsulation of _given a list of jobs, run them all and give me results_.
And uses that for 2 use cases:
- compare - given 2 lists: datasets and models, create cross product of them and run all the jobs.
- launch - given list of (dataset, model), run them all.
=> Introduce Session as a job executor to support use cases other than compare.

src/gretel_trainer/benchmark/__init__.py, src/gretel_trainer/benchmark/log.py
This ensures default logging is still configured the way we want (e.g. INFO for all `gretel_trainer.benchmark` loggers, no duplicate output in Colab, etc.) without polluting the user's environment with variables like `logger`, `handler`, `time_format`, etc.
This also matches the setup in `relational`.
=> Move benchmark log setup out of init
